### ISSUE TITLE
import之后无法注册

### ISSUE THREAD

**Issue by inkscar1** [mariomka/vue-datetime#1]
npm安装后通过import引入，然后一直报错组件无法引入，不知道什么原因

**Comment by mariomka** [comment]
I'm sorry I don't understand Chinese. Anyway, I've translated your message with Google Translator but I need more information like error messages, a code snippet, steps to reproduce or something similar.

**Comment by inkscar1** [comment]
I'm sorry, I'm so used to asking questions in Chinese, and I don't describe the problem clearly,
first,i used `npm install vue-datetime --save` to install it ,it's successed in node_modules.
and in  `main.js`  used `import dateTime from 'vue-datetime' ` and `Vue.use(dateTime)` . 
 and then i started it in  my pages,but it never take effect,
`vue.esm.js?6580:571 [Vue warn]: Unknown custom element: <dateTime> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`  
Yes, you guessed it....  I'm using Google Translator  , too

**Comment by mariomka** [comment]
Files didn't publish on NPM correctly. Update to last version `v.0.3.1`.

**Comment by fuoridallarete** [comment]
> Files didn't publish on NPM correctly. Update to last version `v.0.3.1`.

Sorry, I didn't quite get what to do. When installing what should I type in the controller, instead of ```yarn add luxon vue-datetime weekstart```? I am using Yarn not npm.

Thank you @mariomka
