### ISSUE TITLE
Possibility to unset model

### ISSUE THREAD

**Issue by gaelgf** [mariomka/vue-datetime#10]
It would be cool to have the possibility to unset a value previously set.
I tried to implement it on my side but when i set the model to an empty string, the value watcher fires an error:
**Error in callback for watcher "value": "TypeError: Cannot read property 'clone' of null"**

**Comment by mariomka** [comment]
I hope I can fix it this weekend

**Comment by gaelgf** [comment]
Thank you, my feature works now!
