### ISSUE TITLE
[Vue warn]: Invalid prop: type check failed for prop "auto". Expected Boolean, got String.

### ISSUE THREAD

**Issue by orla11** [mariomka/vue-datetime#100]
## Versions
- vue: ^2.5.7
- vue-datetime: ^1.0.0-beta.6
- luxon: ^1.3.3

### Description:
passing auto="true" property to component generate following warning in console:

"[Vue warn]: Invalid prop: type check failed for prop "auto". Expected Boolean, got String.

found in

---> \<DatetimePopup\>
       \<TransitionGroup\>
         \<Datetime\>
           \<Root\>"
### Steps To Reproduce:
add auto property:

\<datetime  class="theme-grape" format="dd/MM/yyyy" auto="true"\>\</datetime\>

**Comment by mariomka** [comment]
Just set `auto` or `:auto="true"`, otherwise Vue treat value as string.

`<datetime class="theme-grape" format="dd/MM/yyyy" auto></datetime>`
