### ISSUE TITLE
[Vue warn]: Invalid prop: type check failed for prop "inputClass". Expected String, got Object.

### ISSUE THREAD

**Issue by rorymcdaniel** [mariomka/vue-datetime#105]
## Versions
- vue: 2.5.17
- vue-datetime: 1.0.0-beta.8
- luxon: 1.4.4

### Description:
Setting the input class in a conditional manner produces this warning, but still works as expected:

### Steps To Reproduce:
Use the following:
```
 <datetime v-model="completionDate" id="datepicker1"
                             :input-class="{ 'is-invalid': completionDateError, 'form-control': true }"></datetime>
```

https://jsfiddle.net/9mxc4w1j/2/

**Comment by mariomka** [comment]
Fixed in 1.0.0-beta-9.
