### ISSUE TITLE
Screen Reader and Keyboard Accessibility

### ISSUE THREAD

**Issue by MarioLopezDispenser** [mariomka/vue-datetime#107]
## Versions
- vue: 
- vue-datetime:
- luxon:

### Description:
I am interested in adding both screen reader and keyword accessibility functionality to your date time picker component.
Via aria-labels I would like to provide the functionality for screen readers to read aloud:

    Instructions of how to navigate the component with arrow keys when entering the component
    the updated and chosen date and time
    keys pressed to navigate the different date and time rows and columns

For keyboard accessibility, via event-listeners I would like to add arrow key event listeners to:

    Navigate calendar and time picker rows and columns with arrows keys
    Type in number to jump to date number, hour, minute
    Enter the date time picker with TAB and exit with ESC
    To be able to enter characters directly into the date/time field

I have reviewed the CONTRIBUTING.md file; will you be available to assist with getting the PR merged quickly to meet my time constraints (mid December)?

Regards,
Mario

### Steps To Reproduce:

Including a reproduction would be great. You can fork this fiddle: https://jsfiddle.net/ofc30uv3/

**Comment by mariomka** [comment]
I'm sorry, I had not enough time in the last months... If you are willing to add this please re-open this issue.

**Comment by drdrak3** [comment]
We require this functionality as well, has there been any work on accessibility?

**Comment by MarioLopezDispenser** [comment]
Sorry no our team went another route.
