### ISSUE TITLE
only show a subset of minutes

### ISSUE THREAD

**Issue by kermorgant** [mariomka/vue-datetime#11]
Hi,

First, thanks for your component !

It would be nice if there was a way to introduce some stepping for the list of minutes (for example every 5 or 15 minutes).

**Comment by mariomka** [comment]
Sound good but isn't a priority for me, maybe when I have time...

Pull requests are welcome.

**Comment by kermorgant** [comment]
I willl try to find some time to do that in the coming days. 

Basically, my idea would be to add a prop "minutes" taking an array as argument, and give it the current util.minutes() return value as default value.

**Comment by gborcherds** [comment]
I created a pull request for this, along with hours. It should be pretty straightforward if you can accept.

@kermorgant I did pretty much what you were asking for here.

**Comment by mariomka** [comment]
New version (see #28) includes parameters to set hour step and minute step.
