### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by serkandemirel0420** [mariomka/vue-datetime#111]
## Versions
- vue:
- vue-datetime:
- luxon:

### Steps To Reproduce:

Is it possible to change the week and month names to another language? Seems like "momentLocale" does not work.

**Comment by thattejada** [comment]
@serkandemirel0420 have you seen the [internationalization part](https://github.com/mariomka/vue-datetime#internationalization)? I used that config to put the picker into Spanish and worked for me

**Comment by serkandemirel0420** [comment]
oh sorry, missed that part. i will take care of it. Thanks!
