### ISSUE TITLE
How to change the input format of the date passed via v-model?

### ISSUE THREAD

**Issue by victorpinheiro** [mariomka/vue-datetime#115]
## Versions
- vue: 2.5.2
- vue-datetime: 1.0.0-beta.8
- luxon: 1.8.2

### Description:
I know that to use this component correctly, the input format should be something like 2018-12-10T23:02:28.037Z , but my API returns the date as 2018-12-05 12:51:35, and I cannot use this awesome date picker. Is there any way to make it work properly?

### Steps To Reproduce:

My question is how would it be possible to make vue-datetime work when my input date is in this format:
https://jsfiddle.net/5m3sbyt2/

**Comment by victorpinheiro** [comment]
I've done some workaround when receiving the data. Not the best solution, but still works. Closing Issue.

**Comment by milo526** [comment]
I am currently experiencing the same problem, could you post your solution here so others can benefit from it?

**Comment by victorpinheiro** [comment]
What I made was just parse the input date to string on my request then manipulating the string to the format that the date-picker needs. Not sure if it will work on every scenario, but worked for me.
Something like this:

`function parseDate(date) {
	return date.split(' ')[0].split('/').reverse().join('-') + 'T' + date.split(' ')[1]
}`

Edit: The input date format was something like this: '31/12/2018 17:21:0003'
Edit 2: I believe you could do the same using moment.js for a better and cleaner solution
