### ISSUE TITLE
CSS Styles not loading?

### ISSUE THREAD

**Issue by shuegelm** [mariomka/vue-datetime#117]
## Versions
- vue: 2.5.17
- vue-datetime: ^1.0.0-beta.8
- luxon: ^1.8.2

### Description:
CSS Styles not loading?

### Steps To Reproduce:

Including a reproduction would be great. You can fork this fiddle: https://jsfiddle.net/ofc30uv3/
Created Template where I'm using your awesome module:

```
<template>
    <div>
...
               <div class="form-group col-12 col-sm-6 col-md-4 col-lg-4 col-xl-3">
                   <label for="request.away_end_date">Letzter Tag der Abwesenheit</label>
                   <datetime type="date" v-model="request.away_end_date" id="request.away_end_date" placeholder="Datum auswählen"></datetime>
                </div>
...
    </div>
</template>
<script>
    import {Datetime} from 'vue-datetime'
    // You need a specific loader for CSS files
    import 'vue-datetime/dist/vue-datetime.css'
    // use(Datetime);
    import { Settings } from 'luxon'
    Settings.defaultLocale = 'de';

...
</script>
```

Added this to the app.scss
```
// Datetime CSS
@import '~vue-datetime/dist/vue-datetime.css';
```

I checked the folder there is an empty vue-datetime.css. I dont think thats the way it should be, right?
Folder: node_modules/vue-datetime/dist/vue-datetime.css

**Comment by serkandemirel0420** [comment]
+1

**Comment by shuegelm** [comment]
> +1

You can add a class to the input field with:

```
            <datetime
                type="time" v-model="gridunit.start_time"
                id="gridunit.start_time"
                input-class="form-control"
                placeholder="Startzeit auswählen"
                :minute-step="5"
            ></datetime>
```

**Comment by mariomka** [comment]
The CSS file isn't empty, but it has a lot of empty lines (I don't know why). You can see it if scroll a bit: https://unpkg.com/vue-datetime@1.0.0-beta.10/dist/vue-datetime.css

Can you try the minimized version `vue-datetime.min.css`?

**Comment by adnumaro** [comment]
The empty lines could be solved with this in the build.js

``` 
write(`dist/${name}.css`, new CleanCSS({ format: 'beautify', level: 0 }).minify(result).styles)
``` 

The level to 0 disabled all cleanCss options, format: 'beautify' is shorthand to make the css file readable like this:

```
.vdatetime-fade-enter-active,
.vdatetime-fade-leave-active {
  transition: opacity .4s
}
.vdatetime-fade-enter,
.vdatetime-fade-leave-to {
  opacity: 0
}
.vdatetime-overlay {
  z-index: 999;
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  background: rgba(0, 0, 0, .5);
  transition: opacity .5s
}
```

see: [formatting-options](https://github.com/jakubpawlowicz/clean-css#formatting-options)
and: [level-0-optimizations](https://github.com/jakubpawlowicz/clean-css#level-0-optimizations)
of clean-css

**Comment by danielleeas** [comment]
any solution for this issue ?

**Comment by danielleeas** [comment]
not working minimize css file too
![image](https://user-images.githubusercontent.com/28510084/51883312-38862680-2337-11e9-929b-a8d3a64530db.png)
============
![image](https://user-images.githubusercontent.com/28510084/51883324-4b006000-2337-11e9-8cf6-aa45890dac05.png)

**Comment by boriskogan81** [comment]
+1

I'm importing like this: 

`import Datetime from 'vue-datetime';
import 'vue-datetime/dist/vue-datetime.min.css';
Vue.use(Datetime);
`

and adding the element like this:
`          <datetime type="datetime" input-class="form-control" v-model="newSession.end">
            Session End
          </datetime>
`

and the datepicker is not visible, though if I click on it, it opens up.

**Comment by tomrembrown** [comment]
I get the vue-datetime to work properly in my component with the following:
`import { Datetime } from 'vue-datetime';`
at the top of the <script>
Then:
`@import '/node_modules/vue-datetime/dist/vue-datetime.min.css';`
at the top of the <style>
I am using <style lang="scss"> and I have the sass-loader installed in my webpack config in order to get the @import statement to work for the css.

This is my component (or a portion of it):

```
<template>
  <div class="container">
    <form action class="sky-form">
      <header>Create New Event</header>
      <fieldset>
        <div class="row align-items-center">
          <div class="col-md-12">
            <h2>Time and Date</h2>
          </div>
        </div>
        <div class="row align-items-center">
          <div class="col-md-6">
            <section>
              <datetime v-model="date" type="datetime" input-class="myInput" input-id="startTime">
                <label for="startTime" slot="before" class="label">Start Date and Time</label>
                <div class="note" id="startTimeHelp" slot="after">Enter the start date and time of the event</div>
              </datetime>
            </section>
          </div>
          <div class="col-md-6">
            <section>
              <datetime v-model="date" type="datetime" input-class="myInput" input-id="endTime">
                <label for="endTime" slot="before" class="label">End Date and Time</label>
                <div class="note" id="endTimeHelp" slot="after">Enter the end date and time of the event</div>
              </datetime>
            </section>
          </div>
        </div>
        
      </fieldset>

      <footer>
        <button type="submit" class="button">Submit</button>
        <button type="reset" class="button button-secondary">Reset</button>
      </footer>
    </form>
  </div>
</template>

<script>
import { Datetime } from 'vue-datetime';

export default {
  components: {
    'datetime': Datetime
  }
};
</script>

<style lang="scss" scoped>
@import '/node_modules/vue-datetime/dist/vue-datetime.min.css';

.vdatetime input {
  border-color: red !important;
}

.vdatetime {
  border-color: red !important;
}

.vdatetime-input input {
  border-color: red !important;
}

.vdatetime-input {
  border-color: red !important;
}

.myInput {
  border-color: red !important;
}

</style>
```

I should be overriding the styles of the input box in about 5 different ways - but none seem to make its border red.

It does look very nice when I click on it and the date time picker comes up though.

**Comment by greeneggs07** [comment]
haha stupid answer, but this is how I got here.  Make sure you have the loader registered in webpack config:
`      {
        test: /\.css$/,
        use: [
          { loader: 'css-loader' }
        ]
      }
`
