### ISSUE TITLE
Custom trigger

### ISSUE THREAD

**Issue by johannesholmberg** [mariomka/vue-datetime#121]
Is it possible to open the dialog on a custom trigger? I would like to not show the input field itself and just open the date picker dialog when I click on a button. The date is then saved to the state through vuex.

**Comment by scottdotau** [comment]
You can assign the component a ref and then set it's `isOpen` property:

```html
<datetime
    v-model="date"
    type="datetime"
    ref="dateTimePicker">
</datetime>
<button @click="$refs.dateTimePicker.isOpen = true">Open Datepicker</button>
```

**Comment by johannesholmberg** [comment]
@scottgearyau Worked great, thanks!

**Comment by shafeeqBarram** [comment]
@scottgearyau  great ! thank you

**Comment by nil09** [comment]
**To Hide Input Field**
`<datetime ref="dateTimePicker" input-class="form-control d-none"></datetime>`
**Important** d-none bootstrap css class  

**To Open Date Picker on Button @click**
`<button class="btn btn-primary"  @click="$refs.dateTimePicker.isOpen = true">Calendar</button>`

Thanks to @scottgearyau

**Comment by matteopolati** [comment]
Could it be a good approach to override plugin 'open' method?
In this way you could manage modal open programmatically.

Like that:

```javascript
import {
	Datetime
} from 'vue-datetime'
export default {
    name: 'CustomDateTimePicker',
    extends: Datetime,
    methods: {
        /**
         * Override open method in vue-datetimepicker
         * to be fired only programmatically
         */
        open () {
            return false
        }
    }
}
```
