### ISSUE TITLE
Blurry text open datetime

### ISSUE THREAD

**Issue by xFeXx** [mariomka/vue-datetime#123]
## Versions
- vue: 2.5.17
- vue-datetime: 1.0.0-beta.10
- luxon: 1.10.0

### Description:
When opening the datetime_popup the text appears blurry in webkit browsers. 
Problem is described here: https://stackoverflow.com/questions/27385126/chrome-font-appears-blurry/42256897#42256897

A easy fix could be setting a fixed height or changing the modal to flexbox.

My solution was:
```
.vdatetime-popup {
        height: 520px;
        -webkit-font-smoothing: subpixel-antialiased;

        @media screen and (max-width: 768px) {
            height: 470px;
        }
}
```

**Comment by vincent-kean** [comment]
I just change height to even number and it fixed

**Comment by the94air** [comment]
it's not a good idea to make the parent element take a specific height while the content is subject to change in height. A better permanent fix is to calculate the vertical transform `transform: translateX(-50%) translateY(calc(-50% - .5px));`. I would love to make a PR if it's needed @mariomka :+1:
