### ISSUE TITLE
[Feature request] When using type "time" set default selected time

### ISSUE THREAD

**Issue by dasmikko** [mariomka/vue-datetime#140]
### Description:
It would be really nice, if we were able to set the default time picker time.

So instead of it defaulting to current time, it could default to 00:00, or whatever you set it to.

Like so.
![image](https://user-images.githubusercontent.com/4254869/55945172-8cbc5980-5c4a-11e9-8295-7d6742d2ee0b.png)

**Comment by dasmikko** [comment]
changed title

**Comment by stripedbug** [comment]
I guess you can do this by bindind component to a model.

**Comment by mariomka** [comment]
As stripedbug said you can bind a model using `v-model`
