### ISSUE TITLE
Selecting day in following month actually selects previous day

### ISSUE THREAD

**Issue by ftiersch** [mariomka/vue-datetime#141]
## Versions
- vue: 2.6.7
- vue-datetime: 1.0.0-beta.10
- luxon: 1.11.3

### Description:
I have a weird bug in one of my projects. Using the component like this:

```
<datetime
                                        v-model="filterData.from"
                                        type="date"
                                        :auto="true"
                                        :format="'dd.LL.yyyy'"
                                        @input="refresh"
                                ></datetime>
```

I prefill the "from" value with a date one month ago (so for example March 12th). Now I open it, select a date in the same month (March 15th). Then I open it and select a date in the NEXT month (April 10th). 

Invariably it selects the day BEFORE the one I have selected (so April 9th). From what I've seen this only happens if I select a date in this month first and then the next month. If I directly select April 10th it works as expected. Same if I select March 15th and afterwards March 27th - no problem. 

I am a little lost what could cause this. Any pointers would be very welcome.

**Comment by leonmak** [comment]
did you set an initial value for the model data?

**Comment by ftiersch** [comment]
It gets initialized with null but then (after an ajax call has finished loading some data) filled with an initial value, yes. The value is also displayed correctly.

**Comment by stefanknegt** [comment]
I have a similar issue where for instance 01-07-2019 turns into 30-06-2019 somehow. Is there already a solution for this problem?

**Comment by kozki** [comment]
Add prop value-zone="local" and it should be ok. Take a look at #61.

**Comment by puremana** [comment]
Adding both `value-zone="local" zone="local"` fixed this issue for me, I think this issue can be closed now

**Comment by hypetechnologies2019** [comment]
> Adding both `value-zone="local" zone="local"` fixed this issue for me, I think this issue can be closed now

Yes. And did u also set mindate and maxdate? then it doesnt work.

**Comment by rsalunga29** [comment]
I was having this issue too. I followed @puremana 's solution and my issue got fixed
