### ISSUE TITLE
more format's

### ISSUE THREAD

**Issue by dlishtvan** [mariomka/vue-datetime#142]
### Description:
For example choose only year || date || months

**Comment by dlishtvan** [comment]
I found. There is default props "flow"

**Comment by algates90** [comment]
Is it possible to use flow only to choose month or year ? or just month and year ?

**Comment by dlishtvan** [comment]
> Is it possible to use flow only to choose month or year ? or just month and year ?

```
props: {
    flow: {
      type: Array,
      default: () => ['date', 'month', 'year']
    },
}
```

if you want only month, use `default: () => ['month']`
