### ISSUE TITLE
Question about timezones

### ISSUE THREAD

**Issue by tzaitoun** [mariomka/vue-datetime#147]
I am trying to put a max-date based on any timezone a user's "assets" are in. I am using moment to get timezone dates.

```
<datetime
    v-model="date"
    zone="Asia/Tokyo"
    value-zone="Asia/Tokyo"
    :max-datetime="dateNow">
</datetime>
```

I am passing date and dateNow as
`moment().tz('Asia/Tokyo').format()` 
which is as ISO 8601 string and these dates are right (it returns the local time in Tokyo). However, when I open the day picker, May 24 is disabled even though it is currently May 24 7:06 am in Tokyo.

I would appreciate any help, thank you.

**Comment by andreguerrerosilvera** [comment]
Hi @tzaitoun, I had the same question. In my case, I wanted to set the `value-zone` for Colombia and this works for me:

```
value-zone="UTC-5"
```

I think in your case for Tokyo, should be `value-zone="UTC+9"`.

**Comment by mariomka** [comment]
Timezones are managed by luxon, check the following link: https://moment.github.io/luxon/docs/manual/zones.html
