### ISSUE TITLE
minDate and maxDate not working for minutes and hours

### ISSUE THREAD

**Issue by masquel** [mariomka/vue-datetime#15]
When using minDate and maxDate with minutes, you still can select minutes and hours in time picker out of range

**Comment by rayax86** [comment]
+1 as this is very important.

**Comment by mariomka** [comment]
Initially, min and max dates weren't meant to limit the time. Sounds good but I need some time to implement it. Pull request are welcome if anybody has time.

**Comment by mariomka** [comment]
Working on the new version (see #28).
