### ISSUE TITLE
Please and typescript support

### ISSUE THREAD

**Issue by vladislavmega** [mariomka/vue-datetime#152]
Please and typescript support

**Comment by renepeinl** [comment]
I would be greatful about typescript support as well.

**Comment by About7Sharks** [comment]
+1

**Comment by olavorn** [comment]
Since I just needed the import definition working, I started a DefinitelyTyped definition shell.

``` ts
import { VueConstructor } from 'vue';

export const Datetime: VueDateTimeConstructor;
export const DatetimePopup: VueDateTimeConstructor;
export default Datetime;

export interface VueDateTimeProps {
}

export interface VueDateTimeData {
}

export interface VueDateTimeWatch {
}

export interface VueDateTimeMethods {
}

export interface VueDateTimeComputed {
}

export interface VueDateTimeConstructor extends VueConstructor {
    props: VueDateTimeProps;
    data: () => VueDateTimeData;
    watch: VueDateTimeWatch;
    methods: VueDateTimeMethods;
    computed: VueDateTimeComputed;
}
```
Feel free to make suggestions in order to make the first submit.

Repo for PR eventually is here :
https://github.com/ExodusSistemas/DefinitelyTyped

**Comment by olavorn** [comment]
@vladislavmega , @renepeinl , @mariomka 

I think a review in this PR might help:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38428/files

**Comment by UddyOrizu** [comment]
@vladislavmega  You could also use https://github.com/microsoft/dts-gen

**Comment by mariomka** [comment]
It isn't planned to add Typescript support.

**Comment by olavorn** [comment]
@mariomka it is [already suported](https://github.com/mariomka/vue-datetime/issues/152#issuecomment-532649184) via @types/vue-datetime.

**Comment by mariomka** [comment]
Nice!
