### ISSUE TITLE
On edit form how to show the database saved date default as value ?

### ISSUE THREAD

**Issue by irfanDC** [mariomka/vue-datetime#153]
It is great module, only facing issue while displaying database saved values on edit form so the datetime picker should start from the input value. 

<datetime v-model="item.start_date" 
                                    use12-hour format="yyyy-MM-dd HH:mm:ss" 
                                    v-bind:value="item.start_date"  
                                    type="datetime" auto-continue>
                                    </datetime>

**Comment by mohdabbas** [comment]
I am facing the same issue!!!

**Comment by mariomka** [comment]
You can provide initial value with `v-model`.
