### ISSUE TITLE
Is it possible to select only month and year, without day or time? 

### ISSUE THREAD

**Issue by tamerkalieh** [mariomka/vue-datetime#157]
## Versions
- vue: 2.6.10
- vue-datetime: ^1.0.0-beta.10
- luxon: ^1.16.0

### Description:
Is it possible to select only month and year, without day or time?

**Comment by wishinghand** [comment]
You can sort of do this by adding this prop:

`:flow="['month', 'year']"`

The day still shows up though. I'm about to try changing the `format` prop.

**Comment by ovvval** [comment]
Hi @wishinghand 
Thanks for the help. Have you changed the format prop yet and does it work?
Cheers

**Comment by wishinghand** [comment]
It halfway works. I inserted this prop: `format="LL-yy"` and when the user selects a date, they will only see month/year digits in the input. July 2020 will look like `07-20`. 

**However**, when the user first clicks the input to start the selection process, today's date will be displayed next to the month in the colored header of the calendar. How to hide this, I do not know. They cannot change it, and the output will be what you desire, but it's still a small UX snag.

**Comment by acjxwg** [comment]
i try to change 'vue-datetime.css' to hide the header of the calendar
