### ISSUE TITLE
Transition when opening calendar is not smooth

### ISSUE THREAD

**Issue by claide** [mariomka/vue-datetime#16]
This is a front-end stuff related issue I encountered when using the calendar show at the top of modal form. So basically, I have a modal form that has a date field on it and when clicking on the date field it will open the calendar but the transition upon opening it is not smooth in my end. I think there's some glitch in it happens.

I tried adding some css to make it at the top of all elements but the issue still exist. I dunno if you can replicate this one. 

**Note: This only happens at the very start opening the calendar.**

![calendar_issue](https://user-images.githubusercontent.com/12812348/32875038-cd88ea44-cad0-11e7-8485-116aab43fb7c.PNG)

**After a couple of seconds** 

![calendar_issue-1](https://user-images.githubusercontent.com/12812348/32875194-7c418186-cad1-11e7-8d7b-5dce8e619a9c.PNG)

**Comment by claide** [comment]
Oh, I fixed it now by overriding the transitions. Thanks!

**Comment by djob** [comment]
@claide could you please share your solution?
