### ISSUE TITLE
vue-datetime calendar persists on first slide

### ISSUE THREAD

**Issue by rishabhgoel9797** [mariomka/vue-datetime#167]
vue-datetime persists if i used this with carousel. For example i have a carousel with 3 images with start and end time option. But when i open datetime in 2nd or 3rd slide or image it always opens on 1st slide. My datetime component is in v-for. Value is getting edited perfectly. Just the design issue. Please check
![Screenshot 2019-08-19 at 11 14 55 AM](https://user-images.githubusercontent.com/22225114/63242039-8a5eb180-c273-11e9-9b83-cadf4ed61104.png)

**Comment by mariomka** [comment]
Re-open if you can provide a reproduction.
