### ISSUE TITLE
Time issue

### ISSUE THREAD

**Issue by gerryats** [mariomka/vue-datetime#17]
Hi @mariomka 
Selected time does not match with the data model. It shows the server time. Same happens in the provided demo.

**Comment by mariomka** [comment]
Component returns an ISO 8601 UTC date, but user select date in his time zone.

**Comment by gerryats** [comment]
Shouldn't it returns the same selected datetime ?

**Comment by mariomka** [comment]
You can convert from UTC timezone to another one after getting the input.

**Comment by gerryats** [comment]
yes I'm doing it like that now.
But still wouldn't it make more sense to return same datetime. Because datetime that getting set in input field is same as selected datetime but `v-model` attribute return different datetime

**Comment by mariomka** [comment]
The current behavior is the expected. I added a section in the readme to clarify.
