### ISSUE TITLE
Click on a date and get a previous one

### ISSUE THREAD

**Issue by webfelipemaia** [mariomka/vue-datetime#176]
## Versions
- vue: 2.6.10
- vue-datetime: 1.0.0-beta.10
- luxon: 1.19.3

### Description:
When you choose a data or entry, you receive data from the day before the chosen one. If I click on 30, I get 29. On first use. This happens on the first use. Once I try to choose again it works normally.

**Comment by dnnsldr** [comment]
I am getting the same thing. 
Vue 2.6.10
vue-datetime: 1.0.0-beta.10
luxon: 1.19.3

**Comment by monchoz** [comment]
Add prop `value-zone="local"`

**Comment by webfelipemaia** [comment]
yes without the colon
it works
