### ISSUE TITLE
Error in page after pack files

### ISSUE THREAD

**Issue by lwenn** [mariomka/vue-datetime#18]
Hi, I use `vue-datetime` and `moment` in my project, and I change the attribute `locale` of the datetime component to value `zh-cn`, then it's ok when I run in `npm run dev`. However, I pack all files by `npm run build` and open the page, there is error like this when click the datetime DOM:

> TypeError: Cannot read property 'weekdaysMin' of null
    at Object.r [as weekdays] (index.js:formatted:13497)
    at s.weekdays (index.js:formatted:13497)
    at fs.get (index.js:formatted:13497)
    at fs.evaluate (index.js:formatted:13497)
    at s.weekdays (index.js:formatted:3642)
    at s.render (index.js:formatted:13497)
    at s.e._render (index.js:formatted:13497)
    at s.r (index.js:formatted:3480)
    at fs.get (index.js:formatted:13497)
    at fs.run (index.js:formatted:13497)

Would you help to check what wrong? Thank you.

**Comment by mariomka** [comment]
Can you provide a reproduction? A small project in a repository or something similar...

**Comment by lwenn** [comment]
Hi, I find the version I used is `0.5.2`, then I update to `0.6.0`, and there is no error using `locale`, but the same error using `moment-locale`. You could see my reproduction in [vue-datetime-sample](https://github.com/lwenn/vue-datetime-sample), it may provide help.

**Comment by mariomka** [comment]
`locale` property was renamed by `moment-locale`.

About the error, it seems that `UglifyJsPlugin` is breaking something, I'm trying to found a solution.

**Comment by shanjixiaboss** [comment]
I can't use it after build

**Comment by art0s** [comment]
Hello!
I confirm this error in 0.7.0 version
after "npm run build" command 
appears error:

![image](https://user-images.githubusercontent.com/1038217/33700196-5b20c366-db4a-11e7-8d10-b4fc2c56d850.png)

in 0.5.3 everything is clean

**Comment by cruonline** [comment]
Hey guys, any progress?

I'm also trying to locate exact problem.
I can confirm, it is UglifyJsPlugin cousing this **only** while using locale or moment-locale prop.
So it's clearly connected to moment.js

Did anyone tried to switch moment version or other tricks that may help patching this.?

**Comment by art0s** [comment]
we waiting component's update ))
https://github.com/mariomka/vue-datetime/issues/28

**Comment by cruonline** [comment]
If anyone needs fast and dirty fix, just set **keep_fargs** to **true** in **uglyfyjs** options. Works fo me.

**Comment by shanjixiaboss** [comment]
@cruonline  sure? but that's `default` is `true`,  i just used default lang then build all right

**Comment by cruonline** [comment]
sorry, meant set to **false**. Sorry for confusion. This happens if you try to do mulitask and are not a cyborg ;-)

**Comment by shanjixiaboss** [comment]
Oh, no, it's my mistake. I should go to the eye department. /laugh

**Comment by mariomka** [comment]
Next version is near to be stable but changes are meaningful (see #28) but this error mustn't appear more.
