### ISSUE TITLE
format time input

### ISSUE THREAD

**Issue by fuoridallarete** [mariomka/vue-datetime#180]
## Versions
- vue:
- vue-datetime:
- luxon:

### Description:

https://stackoverflow.com/questions/58417402/format-luxon-time-vuejs

### Steps To Reproduce:

Including a reproduction would be great. You can fork this fiddle: https://jsfiddle.net/ofc30uv3/

**Comment by mariomka** [comment]
Can you provide the versions?
Stackoverflow page doesn't exist.
You can re-open the issue if you wish.
