### ISSUE TITLE
minDateTime Error

### ISSUE THREAD

**Issue by jespinosayt** [mariomka/vue-datetime#181]
## Versions
- vue: 2.6.10
- vue-datetime: 1.0.0-beta.10
- luxon: 1.19.3

### Description:

I am setting min-datetime to 6 hours after from today, but if the time is after 12:00 pm so the min-datetime sets to 18:00 hrs, if I open the calendar, today is disabled but I can continue with hours, but, if I select another day, "today" turns to disabled and I can't select it. but the min-datetime should be today at 18:00 hrs. 

### Steps To Reproduce:

-Set min-datetime 6 hours after same day.
-Set now time or check the picker after 12:00 pm.
-At beginning you can continue with time for today, but if you select another day and want to back today, you can't.

![2019-10-18 10_28_51-Window](https://user-images.githubusercontent.com/53576068/67107526-3d735a80-f192-11e9-8634-3c3c238f2e06.png)
![2019-10-18 10_29_07-Window](https://user-images.githubusercontent.com/53576068/67107527-3e0bf100-f192-11e9-97a7-191951412ae1.png)
![2019-10-18 10_29_20-Window](https://user-images.githubusercontent.com/53576068/67107528-3e0bf100-f192-11e9-95b0-752e8aa1e263.png)

fiddle: https://jsfiddle.net/nh21o083/2/

I hope you can Fix it.

Thank you

**Comment by mariomka** [comment]
I think this is caused by set minimum date-time with a different zone than UTC, I'm searching a solution.

**Comment by mariomka** [comment]
Fixed.

**Comment by jespinosayt** [comment]
Actually I was saw that about UTC and I imagine that were the problem... so thank you for the fix.
