### ISSUE TITLE
Incorrect Date Only on placeholder

### ISSUE THREAD

**Issue by wurlJAM** [mariomka/vue-datetime#189]
## Versions
- vue:^2.5.17
- vue-datetime:1.0.0-beta.11
- luxon:1.21.1

### Description:
The date shown on the mask input, shows one day behind the selected date. but not on the hidden input. on the hidden input. the date is shown correctly. 
### Steps To Reproduce:
initialize the component with any date or no date: 
![image](https://user-images.githubusercontent.com/16125972/68982830-1bd7b400-07ce-11ea-9c89-c9dcebac2148.png)

select 31 dec 2019
![image](https://user-images.githubusercontent.com/16125972/68982846-285c0c80-07ce-11ea-8328-57c8d8b6e0d1.png)
the input shows one day behind the one selected 

![image](https://user-images.githubusercontent.com/16125972/68982870-40339080-07ce-11ea-8bee-fbc8df06cec3.png)

but the data passed to the model is correct: 
![image](https://user-images.githubusercontent.com/16125972/68982896-55102400-07ce-11ea-9557-6ad384879fc9.png)

if you select it again. it will show the incorrect date selected. 

![image](https://user-images.githubusercontent.com/16125972/68982948-7a9d2d80-07ce-11ea-97ab-af3faab00098.png)

same thing happens on the demo: 

![image](https://user-images.githubusercontent.com/16125972/68982991-ae785300-07ce-11ea-847c-47e4ca2099c8.png)

Including a reproduction would be great. You can fork this fiddle: https://jsfiddle.net/ofc30uv3/

**Comment by ankraj077** [comment]
Use `value-zone="local"`.

` <datetime type="date" v-model="date" format="MM/dd/yyyy" value-zone="local"></datetime>`

By default, it is UTC.

**Comment by mariomka** [comment]
I guess it is solved. Re-open if not.
