### ISSUE TITLE
required on input field

### ISSUE THREAD

**Issue by lukqw** [mariomka/vue-datetime#190]
## Versions
- vue:^2.6.10
- vue-datetime:^1.0.0-beta.11
- luxon:^1.21.3

### Description:

I'd like to validate my forms with bootstraps built in custom validation but the input fields have to be set to "required" for it to work. I'd really appreciate this feature

**Comment by mariomka** [comment]
The `required` prop is inherited by the input.

```
<datetime v-model="datetime" required></datetime>
```

**Comment by lukqw** [comment]
thanks :-) wasn't clear for me

**Comment by lukqw** [comment]
Alright I tested it and have the following problem: As you can see in the image, the validation itself works. But only the invalid-feedback for the right input is shown, because in the source code, the div with class invalid-feedback has to come directly after the input field.
![image](https://user-images.githubusercontent.com/39307517/70392968-9074cb80-19e5-11ea-99ce-b363d5d885b2.png)

```<div class="form-row m-2">
              <div class="flex-grow-1 mr-2">
                <label for="contentRegistrationDeadline">Registration deadline</label>
                <datetime type="datetime" v-model="content.registrationDeadline"
                          id="contentRegistrationDeadline"
                          input-id="contentRegistrationDeadline"
                          input-class="form-control mb-1" required>
                </datetime>
                <div class="invalid-feedback">
                  Please select the registration deadline
                </div>
              </div>
              <div class="flex-grow-1">
                <label for="contentLocation">Location</label>
                <input type="text" placeholder="Location" v-model="content.location" class="form-control mb-1"
                       id="contentLocation" required>
                <div class="invalid-feedback">
                  Please enter a location
                </div>
              </div>
```

Is there a way to push the div with invalid-feedback into the div with class vdatetime so it's below the input field? 

You can read more about how the form validation works here if you want: https://mdbootstrap.com/docs/jquery/forms/validation/

**Comment by mariomka** [comment]
Maybe `after` slot can help you?

**Comment by lukqw** [comment]
thanks a lot!
