### ISSUE TITLE
Can't resolve 'vue-datetime'

### ISSUE THREAD

**Issue by rundef** [mariomka/vue-datetime#2]
After installing this module, I get the following error: `Can't resolve 'vue-datetime'`.

I believe it's because the **main** file in `package.json` is `dist/index.js`, but that file doesn't exist because of the .gitignored **dist** folder.

By the way, great job on this module, the demo looks fantastic.

**Comment by mariomka** [comment]
#1 Related

Files didn't publish on NPM correctly because `files` attribute wasn't defined in `package.json`.
