### ISSUE TITLE
Showing the wrong date on input `date` type

### ISSUE THREAD

**Issue by spacedog4** [mariomka/vue-datetime#200]
## Versions
- vue: 2.6.10
- vue-datetime: 1.0.0-beta.11
- luxon: 1.21.3

### Description:
When having just a `date` input, the first selection, select the previous day.

Also, if you open the example below, you'll see that it shows the wrong ISOString like:
selecting `2020-02-03` shows `2020-02-04T00:00:00.000Z`

### Steps To Reproduce:
https://jsfiddle.net/mkv3Lgqa/1/

My zone is "America/Bahia"

**Comment by edalzell** [comment]
@spacedog4 how did you resolve this, I'm having the same issue.

**Comment by kupoback** [comment]
Did you find a solution when you closed this? I'm running into the same issue.

Ah I see the issue is solved [here](https://github.com/mariomka/vue-datetime/issues/176).

**Comment by spacedog4** [comment]
Yes, I probably closed my issue becaused saw this one already solved
