### ISSUE TITLE
Chrome latest browser doesnt work

### ISSUE THREAD

**Issue by algates90** [mariomka/vue-datetime#203]
## Versions
- vue: v2.5.16
- vue-datetime: v1.0.0-beta.8

### Description:
With the vue-datetime set with time-zone as 'Europe\Berlin', the returned timestamp is 2020-02-10T00:00:00.000+25:00 when the date is chosen as 11.02.2020.

Affected Chrome : Version 80.0.3987.87 (Official Build) (64-bit)

**Comment by sciracioglu** [comment]
1.0.0-beta.11 

too

**Comment by sciracioglu** [comment]
if you can write your zone it's working. 
but not value-zone="Europe/Istanbul" 

only zone="Europe/Istanbul"

**Comment by kennethteh90** [comment]
> ## Versions
> * vue: v2.5.16
> * vue-datetime: v1.0.0-beta.8
> 
> ### Description:
> With the vue-datetime set with time-zone as 'Europe\Berlin', the returned timestamp is 2020-02-10T00:00:00.000+25:00 when the date is chosen as 11.02.2020.
> 
> Affected Chrome : Version 80.0.3987.87 (Official Build) (64-bit)

Me too! 
## Versions
* vue: v2.5.17
* vue-datetime: v1.0.0-beta.8

Affected (Android) Chrome : Version 80.0.3987.99
Affected (Desktop) Chrome: Version 80.0.3987.100 (Official Build) (64-bit)

I have both valueZone and zone set to Asia/Singapore and I'm seeing +32.00
If I only set zone, I see just Z (which is also wrong for my purposes, should be seeing +08.00)

**Comment by kennethteh90** [comment]
Okay, this workaround might not work for everyone because Singapore happens not to have changing UTC offsets (daylight saving). But I replaced Asia/Singapore with UTC+8 and the problem is gone (for now).

**Reference:**
https://moment.github.io/luxon/docs/manual/zones.html - Specifying a zone

**Comment by hnnesv** [comment]
If it helps anyone, we managed to address this by updating Luxon to a newer version (`npm update --save luxon`). Seems there's an issue with that library in newer versions of Chrome: https://github.com/moment/luxon/issues/619

**Comment by algates90** [comment]
> If it helps anyone, we managed to address this by updating Luxon to a newer version (`npm update --save luxon`). Seems there's an issue with that library in newer versions of Chrome: [moment/luxon#619](https://github.com/moment/luxon/issues/619)

This worked already for me too !
