### ISSUE TITLE
Option for hint

### ISSUE THREAD

**Issue by calistus** [mariomka/vue-datetime#208]
## Versions
- vue:
- vue-datetime:
- luxon:

### Description:
Add an option to display a hint text on the text box before clicking.

I'm not sure this feature us there already as I cannot see it on the Readme

**Comment by EddyTheDove** [comment]
You can use `:placeholder="'Hint text'"`

**Comment by izshreyansh** [comment]
@EddyTheDove I don't think that works.
As it creates placeholder attribute on `<div class="datetime-picker" placeholder="Hint text">` rather than creating it on input `<input data-v-4bd11526="" type="text" id="tj-datetime-input" autocomplete="off">`
