### ISSUE TITLE
Pre-Select When Value Comes From DB

### ISSUE THREAD

**Issue by amirjavaid0** [mariomka/vue-datetime#209]
How I pre select a value, when I fetch a value from db,

I assigned value to v-model when data fetched in created method, but nothing populated in datetime html input filed

I also tried input event, but input event executes before vue js own created method ,

Kindly help

**Comment by EddyTheDove** [comment]
The value coming from your db is not in the right format. 
My assumption is that your DB returns `2020-04-27` or `2020-04-27 09:00:00` which are not supported formats. 

If you use moment.js you can format your date before assigning to v-model. 

```
this.startDate = moment(dateFromDB).format()
```

Then in v-model you can use `startDate`.

**Comment by mariomka** [comment]
Value requires an ISO 8601 string.
