### ISSUE TITLE
Focus selected time to center of view

### ISSUE THREAD

**Issue by enkota** [mariomka/vue-datetime#213]
When you select the time it would be good to follow native mobile time pickers where the selected time will align to the middle of the view. 

For example, clicking a time further ahead will snap it to the middle.

Mobiscroll do this and think it would be a nice UX improvement - https://demo.mobiscroll.com/jquery/datetime/app-website-usage
 
<img width="263" alt="Screenshot 2020-04-18 at 11 07 42" src="https://user-images.githubusercontent.com/13979799/79634811-d47e9680-8164-11ea-83d1-8c0e9be6798f.png">

**Comment by mariomka** [comment]
At the moment there isn't a plan to change the UX.
