### ISSUE TITLE
I think the 'ok' button clicked and emit the event listener will be usefull

### ISSUE THREAD

**Issue by antstrong** [mariomka/vue-datetime#29]
`<datetime v-model="date"
              type="date"
              input-format="YYYY-MM-DD"
              wrapper-class="my-wrapper-class"
              input-class="my-input-class"
              max-date="2017-12-14"
              min-date="2017-12-10"
              @okbtnCallback="mycallback"
              required></datetime>`

**Comment by mariomka** [comment]
Like a normal input, the `input` event is emitted when the value is changed to working with `v-model`. Maybe you can use it or register a watcher for your model.
