### ISSUE TITLE
Overlay issue during open transition with bootstrap 4

### ISSUE THREAD

**Issue by nekdolan** [mariomka/vue-datetime#30]
I am using bootstrap 4 and during the opening transition the popup is behind the bootstrap elements from a different row (see screenshot). After the transition the popup is above the elements. Tested in firefox and chrome.
![overlay-bug-vue-datetime](https://user-images.githubusercontent.com/715213/34050918-e677cacc-e1bc-11e7-84d3-c5d81e7e31dc.png)

**Comment by palakdhingra** [comment]
Facing the same issue :(

**Comment by mariomka** [comment]
Fixed in #32 please test it.

**Comment by nekdolan** [comment]
Tested. Looks good. Thanks.
