### ISSUE TITLE
Error in year selection (v0.x)

### ISSUE THREAD

**Issue by arunrreddy** [mariomka/vue-datetime#35]
When you change the year and don't click on the date and just click ok, the date is not changing. Suppose, the original date 13/11/2017 and I only change the year to 2016, the desired date should be 13/11/2016 but the output which I get 13/11/2017. The expected behaviour should be that any change month, day or year should trigger an update to change the date to the selected date. The current behaviour is that it is mandatory to trigger a click event (to select the day) after you have selected the year.

**Comment by mariomka** [comment]
The expected behavior is the correct, month and year selectors works like a navigation to see but no modify the date. The problem is the current day, appears to activate when it mustn't be.

**Comment by mariomka** [comment]
In the next release (see #28) year picker works like you describe.
