### ISSUE TITLE
v-model does not preset value

### ISSUE THREAD

**Issue by amustapha** [mariomka/vue-datetime#37]
## Versions
- vue: 2.3
- vue-datetime: 1.0.0-alpha.6

### Description:
I'm unable to preset date. For example
`v-model='date' and date=1368457233 | 2013-01-10T23:02:28.037Z does not relay`

**note the use of | to denote different values not simultaneous

**Comment by mariomka** [comment]
Which version of luxon are you using?

Do you have any error in the console?

The date always must be an ISO 8601, `2013-01-10T23:02:28.037Z` its ok.

Check this fiddle: https://jsfiddle.net/m5Lqdjxf/

**Comment by amustapha** [comment]
Luxon Version 0.3.1.
Thanks. But why does the time displayed in the input field and which is stored in the model variable differnt by 1hr?

**Comment by mariomka** [comment]
By default picker uses local time zone and value is UTC, check `value-zone` and `zone` parameters.
