### ISSUE TITLE
Computed property inputValue not equals value prop

### ISSUE THREAD

**Issue by zmts** [mariomka/vue-datetime#38]
Hi there!

## Versions
- vue: 2.5.11
- vue-datetime: v1.0.0-alpha.6
- luxon: 0.3.1

### Description:
Computed property inputValue not equals value prop. It is properly behavior ?

### Steps To Reproduce:
https://monosnap.com/file/USxloM0JiJTe9PyOJqtSVyHIfrUOLU

### Code:
https://gist.github.com/zmts/4d4cb7ddb6c7107faeb84256b0c951c3

**Comment by zmts** [comment]
In 0.7.1 inputValue prop works fine
https://monosnap.com/file/fLgp2AmHERW5F2HSt1rqMGfpKRtGSP

**Comment by mariomka** [comment]
I think you're editing the value after initializing the component.
Ok, I need to add a watcher to the value. It will be included in next release.
The fix should be this afternoon.

Thank you.

**Comment by mariomka** [comment]
Update to `1.0.0-alpha.7` and try again please.
