### ISSUE TITLE
cant select 00 hour/minute

### ISSUE THREAD

**Issue by bloukrans** [mariomka/vue-datetime#41]
Hello,

## Versions
- vue: 2.5.13
- vue-datetime: 1.0.0-beta.2
- luxon: 0.3.1

### Description:

with :minute-step="15" minute "00" cannot be selected

### Steps To Reproduce:

open complete demo on https://mariomka.github.io/vue-datetime/
tried on current firefox and chrome

**Comment by JosDalhuisen** [comment]
Same problem here. Can't select minute "00" and hour "00". So it actually misses a full hour.

**Comment by mariomka** [comment]
00 hour can't be selected either...
I'll check ASAP.

**Comment by washiraporn** [comment]
I have same problem.Can't select minute "00"

**Comment by AxonC** [comment]
I also have the same problem.

**Comment by mariomka** [comment]
Fixed in the last version 1.0.0-beta.3
