### ISSUE TITLE
Laravel and Carbon

### ISSUE THREAD

**Issue by T0miii** [mariomka/vue-datetime#45]
Is there a way to use the Carbons default format, that is returned by the Laravel Eloquent models?

Like this one:  2018-02-07 13:20:48

**Comment by garrensweet** [comment]
@T0miii This plugin requires the `ISO8601` format, so all you need to do is call `->toIso8601String()` on a Carbon date and it will convert it appropriately.

**Comment by mariomka** [comment]
As said @garrensweet only the ISO-8601 format is accepted.
