### ISSUE TITLE
Some example with date formatting?

### ISSUE THREAD

**Issue by TheAndroidGuy** [mariomka/vue-datetime#49]
In the documentation it says it is string but when i try string i get errors.
I wish there were more examples for using the format.
How can i set this format for example: dd.mm.yyyy

**Comment by gustavo43t** [comment]
The v-model date must be a String in ISO format:
```
data: {
  model: moment("2018-03-10 15:30:00").toISOString() 
  // return   "2018-03-10T15:30:00.000Z"

```

**Comment by TheAndroidGuy** [comment]
Aha, i understand that but i don't know how to set the date formatting (display) on the component.

**Comment by gustavo43t** [comment]
format="{ year: 'numeric',  month: 'numeric', day: 'numeric' }";

https://moment.github.io/luxon/docs/manual/formatting.html

**Comment by TheAndroidGuy** [comment]
Thank you for the help but how do i use tokens for the formatting like this:
https://moment.github.io/luxon/docs/manual/formatting.html#table-of-tokens

**Comment by hoythan** [comment]
don't have a clue

**Comment by mariomka** [comment]
Now format tokens are available.
