### ISSUE TITLE
Invalid prop

### ISSUE THREAD

**Issue by AndresCL** [mariomka/vue-datetime#5]
First of all. Great work. Is really hard to find a well-designed-mobile-friendly component for datetime.

Im playing a bit with this mixed with VueFormly, and Im doing the following:

```

import datepicker from "./views/components/Datepicker.vue"
VueFormly.addType('datepicker', datepicker);

```

Then Im wrapping your component like this:

```

<template>
   <div>
      <label>Datetime</label>
      
      <datetime v-model="model[field.key]"
        placeholder="Choose a Date"
        type="datetime"
        input-format="DD-MM-YYYY HH:mm"
        auto-continue></datetime>
      <error-display :form="form" :field="field.key"></error-display>
</div>
</template>

<script>
import Vue from 'vue'
import baseField from 'vue-formly-bootstrap/src/fields/baseField';
import Datetime from 'vue-datetime';
Vue.use(Datetime);

export default {
   mixins: [baseField]
}
</script>

```

Finally calling it from my Vue-Formly fields:

```

{
          required: true,
          key: 'startDate',
          type: 'datepicker',
          templateOptions: {
            text: 'Data Inicio',
            classInline: true
          }
},

```

The component displays flawlessly, I can select a date and time, and it grabs the data and shows it into the form. The problem is that im getting some errors in console that I would like to solve.

```

1.  [Vue warn]:Invalid prop: type check failed for prop "value". Expected String, got Undefined.
2. [Vue warn]: Error in callback for watcher "value": "TypeError: Cannot read property 'length' of undefined"

```

Can you help me please? And again, thanks for the hard work.

**Comment by mariomka** [comment]
Thank you.

I don't know how to VueFormly works but seems that both `warnings` are showing because `model[field.key]` is `undefined` but it must be a string.

You can see model examples in the [app.js](https://github.com/mariomka/vue-datetime/blob/master/docs/src/app.js) from demo.

**Comment by AndresCL** [comment]
Yes, in fact I wasn't sending those values. Setting my model this way made the trick. So yes, no errors on console.

this.model = {
        title: '',
        startDate: ''
      }

Muchas gracias amigo!

**Comment by mariomka** [comment]
De nada ;)
