### ISSUE TITLE
When moment-locale is not English not works properly

### ISSUE THREAD

**Issue by ghost** [mariomka/vue-datetime#50]
## Versions
- vue: 2.5.13
- vue-datetime: 0.7.1
- luxon: 0.3.1

### Description:
Using vue-cli with webpack.
Languange support does not work well.

Using moment-locale="es" in dev works.
Using the same in production (npm run build) obtain a null error in the locale loading.

But, if you use moment-locale="en" works well.

### Steps To Reproduce:
Use vue-cli with webpack.
Add de component
<datetime ... moment-locale="es" ...></datetime>
npm run dev --> works
npm run build, serve -s dist, --> null exception

**Comment by mariomka** [comment]
Sorry version v0.x is no longer maintained.
