### ISSUE TITLE
Invalid prop: type check failed for prop "format". Expected Object, got String.

### ISSUE THREAD

**Issue by rayax86** [mariomka/vue-datetime#52]
## Versions
- vue: 2.5.13
- vue-datetime: 1.0.0-beta.3
- luxon: 0.3.1

### Description:
The documentation says prop `format` has type `String`. But by providing a string, an `Invalid prop: type check failed for prop "format". Expected Object, got String.` error is thrown.

**Comment by rayax86** [comment]
I noticed you passed the `format` directly to a `DateTime` instance's  `toLocaleString` method. Please revise this as `toLocaleString` expects an instance of `Intl.DateTimeFormat`. There will be no way to use strings to specify the format, which is common.

**Comment by TheAndroidGuy** [comment]
Wait, so it is not possible to use format strings?
Without that, i think this component is not very useful.

**Comment by juanvillegas** [comment]
Is there any solution for this?

**Comment by ale51** [comment]
@juanvillegas 

I can format date.
check [Luxon doc](https://moment.github.io/luxon/docs/manual/formatting.html) about ```DateTime.DATETIME_FULL```.

```
<template>
    <div>
        <datetime v-bind:format="myFormat"></datetime>
    </div>
</template>

<script>
    import {DateTime} from 'luxon';
    export default {
        data() {
            return {
                myFormat: DateTime.DATETIME_FULL
            }
        },
    }
</script>
```

But in this way, I can not specify the format by strings like 'yyyy-mm-dd'
as @rayax86  says

**Comment by mariomka** [comment]
Format tokens are now available.

**Comment by juanvillegas** [comment]
Awesome ill give it a try. thanks!
