### ISSUE TITLE
Unable to make component work

### ISSUE THREAD

**Issue by arunrreddy** [mariomka/vue-datetime#53]
## Versions
- vue: 2.5.2
- vue-datetime: 1.0.0-beta-3
- luxon: 0.5.6

### Steps To Reproduce:
I installed the packages required but not able to locate the css file in the dist file in vue-datetime module in node_modules.
There is not dist file found when installing the package.
I have tried all the possible ways suggested but could not get the datepicker popup to show up.
CSS is breaking. 
Docs are not relevant to the updated version using luxon.

**Comment by mariomka** [comment]
Just import css:

```js
import 'vue-datetime/dist/vue-datetime.min.css'
```

You can see `dist` folder in unpkg for example: https://unpkg.com/vue-datetime@1.0.0-beta.3/dist/
