### ISSUE TITLE
Only allows to select a time greater than current minute

### ISSUE THREAD

**Issue by AndresCL** [mariomka/vue-datetime#6]
Hey mate.

I've discovered one issue. Currently my time is 22:09, I just can select a time greater or equals than 22:10. Dunno if this is lack of my configuration or something, but I don't think so.

![captura de pantalla 2017-11-01 a la s 22 08 21](https://user-images.githubusercontent.com/1790792/32303678-3a7f67f8-bf51-11e7-91e2-c04372fdecb0.png)

**Comment by mariomka** [comment]
The problem was with numbers less than 10. Fixed in the last version.
