### ISSUE TITLE
Question: Use as Time Picker only

### ISSUE THREAD

**Issue by a2exfr** [mariomka/vue-datetime#60]
Is it possible to use only as Time Picker?

**Comment by arturs-buls** [comment]
I looked up at the code earlier since had same question. There is no such option at the moment but I would like to see it. Would be great to use one with one design for all my needs.

**Comment by Spatlani** [comment]
It was there in the previous version (0.7.1), I am waiting for this feature in the newer version.

**Comment by a2exfr** [comment]
as a quick  solution for [time picker](https://github.com/a2exfr/vue-datetime/commit/62460e5a69a3a30c30c8fabb19f616a7eedba0e7)  I do it in my [fork ](https://github.com/a2exfr/vue-datetime)

**Comment by borie88** [comment]
Pull request?

**Comment by mariomka** [comment]
Pull request will be appreciated.

**Comment by s-lee-kwong** [comment]
I would really appreciate this feature officially on the project, if I recreate what @a2exfr has done on his fork and made a pull request, would anyone be opposed? 

Obviously if @a2exfr did it themselves that would be fine but I feel its been a while and haven't seen a pull request yet.

**Comment by mariomka** [comment]
For sure! But don't forget to add tests, please.

**Comment by s-lee-kwong** [comment]
Ya for sure!, I did notice when I forked and ran the tests that one was failing without me changing anything.

✗ should be updated if value is updated

1) should be updated if value is updated
     Datetime.vue input value
     Error: Uncaught AssertionError: expected 'Dec 6, 2017' to equal 'Dec 7, 2017'

**Comment by mariomka** [comment]
Time picker was added in the last version. @s-lee-kwong thanks you. #80

**Comment by borie88** [comment]
Thanks. However, it would be nice if it was just a time string without today's date appended onto it. Not sure how others would have liked this feature
