### ISSUE TITLE
How set format of the selected date to 'YYYY-MM-DD hh:mm' ?

### ISSUE THREAD

**Issue by sergeynilov** [mariomka/vue-datetime#64]
Hello ,
I move my  laravel 5.6 / vue.js 2.5.7/ application 
I use vue-datetime ( vue-datetime@1.0.0-beta.3 ) component
and I need to set format of the selected date to 'YYYY-MM-DD hh:mm' format.
I did not  find how to set it.
All my attemptes to manipulate with format property, like
```
							<datetime
									type="datetime"
									:hour-step="1"
									v-model="event.at_time"
									:minute-step="5"
									:format="{ year: 'numeric', month: 'long', day: 'numeric', hour: 'numeric', minute: '2-digit' }"
									:week-start="0"
									auto
							></datetime>
```

Failed. Which is the right way?

Also if there is a way to get javascript datetime value of the component ?

Thanks!

**Comment by hoythan** [comment]
#65

**Comment by larsjanssen6** [comment]
Same for me.

**Comment by starjou** [comment]
The best I can do is formating as yyyy/mm/dd hh:ii. Dunno how to replace slash to dash yet.
```
:format="{ 
year: 'numeric', 
month: '2-digit', 
day: '2-digit', 
hour: 'numeric', 
minute: '2-digit', 
hour12: false
}"
```

**Comment by mariomka** [comment]
Now format tokens are available.

**Comment by supersirius814** [comment]
Dear mariomka.
How can I change language  of datetime picker?
