### ISSUE TITLE
Bug with minDate

### ISSUE THREAD

**Issue by P4R4DiSi4C** [mariomka/vue-datetime#68]
## Versions
- vue: 2.5.2
- vue-datetime: 1.0.0-beta.3
- luxon: 1.2.1

### Description:
I set the minDate to tomorrow's date, though as you can see on the fiddle, im able to apply the date of "today" by directly clicking on "validate".
### Steps To Reproduce:
1) Set minDate to tomorrow's date or whatever later than today
2) Open the datetime calendar
3) Press directly on validate
4) Confirm the time
5) Done

Fiddle: https://jsfiddle.net/ofc30uv3/5/

**Comment by mvilera** [comment]
Not related to the topic, but the fiddle link points to 404 on Github, might want to fix that.

**Comment by ftbastler** [comment]
+1
Facing the same problem on my application.

**Comment by ftbastler** [comment]
Related to #88 maybe?

**Comment by mariomka** [comment]
I guess this is solved with #93
