### ISSUE TITLE
How to output seconds as 00:00

### ISSUE THREAD

**Issue by dope** [mariomka/vue-datetime#75]
## Versions
- vue: 2.2.0
- vue-datetime: 1.0.0-beta.3
- luxon: 1.2.1

### Description:
I've noticed when selecting a time, there is a random selection of seconds that get added too. Can this be removed? or set to 00:00

### Steps To Reproduce:
- Selecting `4th July 2018: 14:46` on the picker
- Output is: `2018-07-04T14:46:22.723+01:00`

**Comment by mariomka** [comment]
Fixed in the last version `1.0.0-beta.6`
