### ISSUE TITLE
Cannot integrate with vue-form

### ISSUE THREAD

**Issue by andrewhl** [mariomka/vue-datetime#76]
## Versions
- vue: ^2.5.2
- vue-datetime: ^1.0.0-beta.3
- luxon: ^1.3.1

### Description: 
When the component is wrapped in `vue-form`'s `<validate>` tag, it stops working properly. It opens. You can select a date. But closing is impossible, and 'continuing' has strange behaviour (contents of the datepicker disappear).

### Steps To Reproduce: 
See this [codesandbox](https://codesandbox.io/s/50w892rl9l).

Any help would be appreciated.

**Comment by mariomka** [comment]
Codesandbox does not work I get some errors in the console about unregistered components.

I think it can be related to `<label>` tag, datetime component cant be wrapped inside a `<label>` because it has conflicts with focus event.

**Comment by mariomka** [comment]
See #77 

Maybe add the `for` attribute to `label` solves it.

**Comment by steven87vt** [comment]
So just wanted to follow up here, even when nested inside a `<label>` element adding the `for` attribute does the trick. You can still see the label flash in the background during the click events inside the popover but that might be something that can be stopped using native click and stopping propagation.

**Comment by andrewhl** [comment]
Apologies @mariomka. I updated the [sandbox](https://codesandbox.io/s/50w892rl9l). I did remove the `label` and it works properly. Thanks.
