### ISSUE TITLE
Min and Max

### ISSUE THREAD

**Issue by moyvera** [mariomka/vue-datetime#8]
Set min for show only future dates and max to show only past dates according to min and max

**Comment by mariomka** [comment]
Added in last version v0.5.0. Commit: d4e4b05cf94dda17c5ec5750cbd668f8b2103edd

**Comment by muzashi36** [comment]
How can I set timezone of Min Max?

**Comment by mariomka** [comment]
In v0.x isn't possible. And min and max only limit dates, not time.

In v1.x is possible, parameters are an ISO 8601 string.
