### ISSUE TITLE
How can i enable just three day of month 

### ISSUE THREAD

**Issue by hamidh2** [mariomka/vue-datetime#81]
Hey 
i wana this package show only three days of month 
and my question is how can i implement this behavior in my project 
please tell me with an exmple 
thank you

**Comment by ftbastler** [comment]
Hey,
you can do that by setting min-datetime and max-datetime.
See https://github.com/mariomka/vue-datetime#parameters.

**Comment by mariomka** [comment]
Please re-open if you need more help.
