### ISSUE TITLE
If set minDate you can choose years before this minDate

### ISSUE THREAD

**Issue by dimatima13** [mariomka/vue-datetime#89]
## Versions
- vue: 2.5.16
- vue-datetime: 1.0.0-beta.6
- luxon: 1.3.3

### Description:
Then you set minDate for example 2018-09-04T15:10:58.354Z. You can't choose days or months before, it's good. But you can choose years before and confirm it after validate.

### Steps To Reproduce:

You can test it on your "Complete demo" example: https://mariomka.github.io/vue-datetime/ .

**Comment by dimatima13** [comment]
@mariomka

**Comment by ftbastler** [comment]
That's not the case for me.

**Comment by Craft4u** [comment]
@ftbastler What u mean? I don't understand

**Comment by mariomka** [comment]
It was fixed in the last version. #84
