### ISSUE TITLE
vue-moment doesnot work after install vue-datetime

### ISSUE THREAD

**Issue by tanhs** [mariomka/vue-datetime#9]
if i install vue-datetime then it removes the vue-moment, and if I install vue-moment then vue-datetime is removed.  can i have both installed?
i use the following to do installation
npm install vue-moment
npm install vue-datetime

**Comment by mariomka** [comment]
Does Npm output any error or info?

Both repositories have the same version (^2.11.1) of moment.js.

I had created a new repo to try to reproduce and I had no problems. Steps:

```sh
npm init
npm install vue-moment
npm install vue-datetime
```

Can you provide more information or a complete reproduction?

**Comment by tanhs** [comment]
I didn't do npm init, hope that doesn't have any impact.
Result still the same, it removes vue-moment.

Install vue-moment
[image: Inline image 1]
install vue-datetime
[image: Inline image 2]

**Comment by mariomka** [comment]
I created a new project to test it in an isolated environment. Do you have the issue even creating new project?. Can you provide an isolated steps to reproduce it? Maybe the issue is caused by a third package.

PD. Images aren't uploaded correctly

**Comment by tanhs** [comment]
i check on the installation log.  if you look at line 143 it remove the
vue-moment.
i will try to create new project to try.

**Comment by tanhs** [comment]
I tried on new project it works fine.  I am not sure how to fix the old
project and I ended up copy and paste the vue-datetime dir from new to old
project.
Hope it works.

**Comment by mariomka** [comment]
I think a third package has any conflict.
