### ISSUE TITLE
Theming from demo isn't working

### ISSUE THREAD

**Issue by zirlman** [mariomka/vue-datetime#91]
I was trying to theme datetime component following the [demo](https://mariomka.github.io/vue-datetime/) but it won't apply. I've literally just copy-pasted the code from the demo

**Comment by lulul62** [comment]
Same as the op

**Comment by CLSheriff** [comment]
I added the following import statement to main.js:
import 'vue-datetime/dist/vue-datetime.css'

**Comment by ftbastler** [comment]
Could you please provide some example code?

**Comment by CLSheriff** [comment]
// THIS IS MY main.js file

import Vue from 'vue'
import App from './App.vue'
import VueResource from 'vue-resource'
import { Datetime } from 'vue-datetime'
import 'vue-datetime/dist/vue-datetime.css' // <--I added this line

Vue.component('datetime', Datetime);

Vue.use(VueResource)

new Vue({
el: '#app',
data: {
},
render: h => h(App)
})
console.log("JS WORKS")

**Comment by mariomka** [comment]
Probably the styles are being overwritten by the default styles. Add a class with `input-class` prop and use as the root of your custom styles.

I should update the demo.

**Comment by mariomka** [comment]
Never mind my last comment ... The demo is fine.

Just make sure you import the default css, as @CLSheriff  say above and add the corresponding class to component.

Re-open the issue if you can't fix it.
