### ISSUE TITLE
If you have a date range, it's perfect.

### ISSUE THREAD

**Issue by David2k13** [mariomka/vue-datetime#96]
## Versions
- vue:
- vue-datetime:
- luxon:

### Steps To Reproduce:

Including a reproduction would be great. You can fork this fiddle: https://jsfiddle.net/ofc30uv3/

**Comment by mariomka** [comment]
?

**Comment by David2k13** [comment]
It may be that there is a problem with the translation. This project is great. It would be better if you added a daterange feature
